### ISSUE TITLE
GSYNC doesn't work in Fullscreen

### ISSUE THREAD

**Issue by Yossarian82** [uberhalit/EldenRingFpsUnlockAndMore#15]
As per title, GSYNC works correctly in Borderless Windowed, but with Fullscreen it does not work

BTW thanks so much for your hard work!

**Comment by Qunka724** [comment]
I'm also seeing this behavior. I wouldn't mind playing in Borderless Windowed if not for the fact that you can't enable HDR unless you're in fullscreen mode.

**Comment by DubbleClick** [comment]
I'm not sure what you mean, gsync is not related to this launcher.

**Comment by Qunka724** [comment]
I can get gsync working on borderless windowed with the fps successfully unlocked no problem, but going to fullscreen will cap the fps back down to 60. Essentially the behavior I'm seeing is:

- Vsync off, fullscreen: Fps unlocks and HDR works but with unplayable screen tearing.
- Vsync on, borderless windowed: Fps unlocks and gsync works but HDR doesn't work.
- Vsync on, fullscreen: FPS stays capped at 60, but gsync and HDR work.

**Comment by doktorsleepelss** [comment]
> I can get gsync working on borderless windowed with the fps successfully unlocked no problem, but going to fullscreen will cap the fps back down to 60. Essentially the behavior I'm seeing is:
> 
> * Vsync off, fullscreen: Fps unlocks and HDR works but with unplayable screen tearing.
> * Vsync on, borderless windowed: Fps unlocks and gsync works but HDR doesn't work.
> * Vsync on, fullscreen: FPS stays capped at 60, but gsync and HDR work.

Yup, this describes my experience exactly.  I'm on a windows 11 insider build. (220210-1445) and using a oh-not-so-legit copy of Elden Ring. I have a ryzen 5 3600x and 2070 super. Weirdly, I also get a 10 fps drop with borderless, but I think this is unrelated to the mod.

**Comment by DubbleClick** [comment]
Ah I understand, the fps unlock isn't working for fullscreen.

**Comment by Loban79** [comment]
This is the exact behavior I'm seeing as well.  It seems Microsoft has added HDR support to windowed mode in their latest dev channel release if anything wants to try it.
https://www.pcworld.com/article/615360/new-windows-11-build-reveals-new-pc-gaming-hdr-improvements.html

**Comment by tetsugoro** [comment]
You may solve your issue by forcing fullscreen mode to your maximum refresh rate. Unfortunately the game forces 60hz in Fullscreen Exclusive so you have to employ some sort of workaround. In DX12 games you can normally use SpecialK to do this, but this is not compatible with Easy Anti-cheat. VRR also works better in general when the application is set to your maximum refresh rate due to LFC.

What does work is making a custom resolution of 1920x1079 (-1 vertical pixel of your resolution!) at only your highest refresh rate. The game will fallback onto the highest refresh rate if a 60hz mode is not found.

**Comment by tetsugoro** [comment]
> Do you have any example code?
Oh, no. This is all on the user side outside of the game or your mod. Just a workaround suggestion for users intending to use fullscreen exclusive above 60hz for any reason. VRR does work in borderless DX12 even when set to Fullscreen apps only in drivers. So I guess this is mostly useful for HDR+VRR if HDR only works in FS Exclusive mode since you want your monitor at native refresh rate when using VRR.

**Comment by DubbleClick** [comment]
> Would using this mod merely to bypass in-game vsync and cap at 60fps also risk being banned from online?

Yes. The game code is altered at runtime, always leaving you at a risk of a ban. Play offline to be safe, or wait for an officially acknowledged mod to remove the cap (unlikely to happen, sadly). There's about a zero percent chance FromSoftware removes the caps themselves.

**Comment by uberhalit** [comment]
@tofu-dreg See #17

**Comment by uberhalit** [comment]
Version 0.0.0.5 now removes the Hz lock in fullscreen @tofu-dreg @tetsugoro
