### ISSUE TITLE
Crash Report - Tool closes right after launch

### ISSUE THREAD

**Issue by Qunka724** [uberhalit/EldenRingFpsUnlockAndMore#2]
I know the beta just came out an hour ago, but I wanted to document the behavior I'm seeing just in case it might be helpful. The tool launches the game without EAC successfully, but just a moment before the Bandai Namco logo appears the tool crashes. The game continues run, but with the tool crashed there's no way to patch the game. Attempting to run the tool again brings up a prompt saying "Game is already running! Do you want to close and restart it in offline mode without EAC?"

**Specs:**
- Windows 11
- AMD Ryzen 7 5800X 8-Core Processor 3.80 GHz
- GeForce RTX 3080
- 32.0 GB RAM

**Notes about installation**
- I followed the steps for Nvidia to the letter.
- I also followed the GSYNC additional steps, once again to the letter.
- I'm not using ReShade.

**Troubleshooting Attempted:**
- Disabled fullscreen optimization
- Added the game exe and the tool to windows defender exclusions
- Undid the GSYNC additional steps by setting Vertical Sync to Off
- Ran the tool as Administrator

Thank you for your efforts on this project!

**Comment by Yossarian82** [comment]
Yeah I can't click the 'patch game' button either.

**Comment by heryoff** [comment]
Yeah same

**Comment by Woesch-Nich** [comment]
Same for me

**Comment by phx7** [comment]
Same

**Comment by AldoMDC** [comment]
Some feedback...

Faulting application name: EldenRingFPSUnlockAndMore_v0.0.0.1-beta.exe, version: 0.0.0.1, time stamp: 0x952eb391
Faulting module name: KERNELBASE.dll, version: 10.0.22557.1, time stamp: 0x509683d6
Exception code: 0xe0434352
Fault offset: 0x000000000001358c
Faulting process id: 0x0x4F4C
Faulting application start time: 0x0x1D82A416EBF1E4F
Faulting application path: E:\OneDrive\Downloads\Trainers\EldenRingFPSUnlockAndMore_v0.0.0.1-beta.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 706f9df4-9bbf-45b0-a442-65fd984c30d5
Faulting package full name: 
Faulting package-relative application ID: 

Application: EldenRingFPSUnlockAndMore_v0.0.0.1-beta.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileNotFoundException
   at EldenRingFPSUnlockAndMore.PatternScan.FindPattern_Native(Byte[] ByRef, Byte[] ByRef, System.String)
   at EldenRingFPSUnlockAndMore.PatternScan.FindPattern(System.String)
   at EldenRingFPSUnlockAndMore.MainWindow.OpenGame()
   at EldenRingFPSUnlockAndMore.MainWindow+<SafeStartGame>d__9.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Application.RunDispatcher(System.Object)
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at EldenRingFPSUnlockAndMore.App.Main()

Fault bucket 2292997070163165811, type 5
Event Name: CLR20r3
Response: Not available
Cab Id: 0

Problem signature:
P1: RNL1MZJPGYF1V2MYZSQ3XXPSXSO0OYON
P2: 0.0.0.1
P3: 952eb391
P4: EldenRingFPSUnlockAndMore
P5: 0.0.0.1
P6: 952eb391
P7: 20
P8: a9
P9: System.IO.FileNotFoundException
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.b6d9a4c7-bd02-4df6-b021-f756f4b46704.tmp.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.c916e85e-aeae-4407-9c4f-25ab0f8c211b.tmp.WERInternalMetadata.xml
WPR_initiated_DiagTrackMiniLogger_OneTrace_User_Logger_20220225_1 EC_0_inject.etl
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.7c592799-05c4-4a42-bce7-1cc15740c4f0.tmp.etl
WPR_initiated_DiagTrackMiniLogger_WPR System Collector_inject.etl
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.e3023a29-a808-4ff5-8402-7d50825ac121.tmp.etl
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.367232d6-1b54-4eb4-8201-3e7682b03b0c.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.ba2a1b48-cb35-4304-864d-237b610bbf27.tmp.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.9c46800d-f473-46e2-a9bb-309bba12185a.tmp.xml

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_RNL1MZJPGYF1V2MY_54115987eaac4adbd028fc2b589df03ef639e71_c027fea8_05174a55-a5e3-4010-af05-db591a872236

Analysis symbol: 
Rechecking for solution: 0
Report Id: 706f9df4-9bbf-45b0-a442-65fd984c30d5
Report Status: 2147487744
Hashed bucket: e9cd582ffb4ac48d0fd25cafbe164273
Cab Guid: 0

**Comment by Auron110-ita** [comment]
Same issue

**Comment by Pesten1984** [comment]
Exact same issue for me

Windows 10
intel i7 10700KF
GeForce RTX 3080
16 GB RAM @3200 mhz

**Comment by Idanina** [comment]
Same.

Windows 10
i9-9900K
GeForce RTX 2080 TI
32 GB RAM @ 3200 MHz

**Comment by bulaspulas** [comment]
same damn issue for me
gtx 1080
ryzen 7 5800x
win 10
16gb ram 3200mhz

**Comment by mrdellis** [comment]
The error seems to be connected to System.Runtime.CompilerServices.Unsafe .. Had the same error when I tested it in VS and removing the reference to System.Runtime.CompilerServices.Unsafe and readding it fixed the issue

**Comment by OrixTheGod** [comment]
> The error seems to be connected to System.Runtime.CompilerServices.Unsafe .. Had the same error when I tested it in VS and removing the reference to System.Runtime.CompilerServices.Unsafe and readding it fixed the issue

so, how can I fix it to play the game in 144 HZ?

**Comment by mrdellis** [comment]
> > The error seems to be connected to System.Runtime.CompilerServices.Unsafe .. Had the same error when I tested it in VS and removing the reference to System.Runtime.CompilerServices.Unsafe and readding it fixed the issue
> 
> so, how can I fix it to play the game in 144 HZ?

I forked it and uploaded a fix here https://github.com/mrdellis/EldenRingFpsUnlockAndMore/releases/tag/0.0.0.1 ..

Hope it works and fixes your problem..

**Comment by Auron110-ita** [comment]
> > > The error seems to be connected to System.Runtime.CompilerServices.Unsafe .. Had the same error when I tested it in VS and removing the reference to System.Runtime.CompilerServices.Unsafe and readding it fixed the issue
> > 
> > 
> > so, how can I fix it to play the game in 144 HZ?
> 
> I forked it and uploaded a fix here https://github.com/mrdellis/EldenRingFpsUnlockAndMore/releases/tag/0.0.0.1 ..
> 
> Hope it works and fixes your problem..

You are the best, it works perfectly thank you

**Comment by charliik** [comment]
> 

Yo thank you very much, could you implement game files selection when hitting "Start game" please? Because it didnt found the game on my PC and I'm getting an error.

**Comment by mateusmedeiros** [comment]
Thanks for the quick workaround @mrdellis.

Also guys, just a tip that may sound annoying but I swear it's not my intention, cause I know most of you all are probably not developers, so you have zero obligation to know this and it's totally expected that you don't, so you have done nothing wrong at all.

But it's usually not considered good etiquette to add more messages to a github issue just stating that the problem happens with you too (or anything else that doesn't add new info about the problem). If you wanna show some support for the issue to let the maintainer know that there's a lot of people with that same problem, the recommended way is usually to react to the original message of the issue (usually with a 👍).

That's mostly because they may have it set (and I believe this is the github default, too) to get an email with each new message, so they may end up with a pile of messages in their inbox. They already know it's an issue, no matter how many messages they get ;D

Again, not trying to sound condescending nor annoying, and at the end of the day this is my opinion, so it's no more right than anyone else's.

**Comment by bulaspulas** [comment]
> > > The error seems to be connected to System.Runtime.CompilerServices.Unsafe .. Had the same error when I tested it in VS and removing the reference to System.Runtime.CompilerServices.Unsafe and readding it fixed the issue
> > 
> > 
> > so, how can I fix it to play the game in 144 HZ?
> 
> I forked it and uploaded a fix here https://github.com/mrdellis/EldenRingFpsUnlockAndMore/releases/tag/0.0.0.1 ..
> 
> Hope it works and fixes your problem..

i love you

**Comment by uberhalit** [comment]
This should be resolved now. I didn't expect so many people trying this patcher in its first release. Obviously I hadn't added a lot of checks yet. This should be resolved now, please let me now if you encounter any other problems.
