### ISSUE TITLE
Lack of acknowledgment

### ISSUE THREAD

**Issue by l0lhax** [uberhalit/EldenRingFpsUnlockAndMore#54]
Did you at least want to acknowledge the significant work of others for the FOV / aspect / 60hz fullscreen related patches you ripped from Flawless Widescreen? :D

**Comment by duskyBabz** [comment]
I just took a look at the code for the Elden Ring plugin from FWS and didn't see any sign of code being "ripped".
What are you basing your accusation on exactly?

**Comment by l0lhax** [comment]
All the patch positions and mechanisms are the same, including my mistakes, for example - such as calculating delta time with (1000f / fps) / 1000f (it should be 1.0f / 60)

It's fairly obvious.

**Comment by uberhalit** [comment]
Hello, 
I wasn't aware of this tool yet but as I am seeing it on their website, Elden Ring is not listed as a supported title nor is the tool open source?

I am assuming with delta-time you are referring to the frame rate unlock? I released that a few hours after game release and my testers had that ready merely 20mins after midnight on release day as the entire function including this delta-time code segment is copied from my own Sekiro utility which has had that code since 25th of March 2019 which was its initial release on github: https://github.com/uberhalit/SekiroFpsUnlockAndMore/blob/master/SekiroFpsUnlockAndMore/MainWindow.xaml.cs#L887

I am not going to remove your comments as I am definitely not the only person who can come up with patches of an old engine quickly after release. But please consider this next time.
