### ISSUE TITLE
not working (solved)

### ISSUE THREAD

**Issue by sociofall** [uberhalit/EldenRingFpsUnlockAndMore#6]
i have rebuilded app for my own gamepath and don't change anything else. also have followed all the instruction, except setting "Preferred refresh rate" cause there isn't such setting (my monitor is 75hz, maybe that's why). afterall, it doesn't work, and i don't know why.
![изображение](https://user-images.githubusercontent.com/67294769/155733061-f1535894-50bd-4fa5-835f-8f7644ea7b2c.png)
UPD! working xD. I must use checkbox for applying framerate patch.
![изображение](https://user-images.githubusercontent.com/67294769/155740225-fcbef0ee-3797-4b71-83f8-2c5943543fe6.png)

**Comment by w84gg** [comment]
SAME! 
LG G SYNC 144 hz + 1080ti + windows 11
Read all your code in main class. 
All stages passed, running not license steam version with/without steam logging.
I edited registry for true path, game launching but when I switched to your app windows - it just closed after running game, so I even couldn't to patch it (it seems its kind of trick or hack with window activity in PatchGame function that not able for me because main unlock app window closed after running game)
