### ISSUE TITLE
I'm testing the game with the not official version and is opening steam when I launch the game

### ISSUE THREAD

**Issue by Elysiumss** [uberhalit/EldenRingFpsUnlockAndMore#65]
This makes my controller not work at all.

Any fix to make steam stop launching when I open the game using the Fps unlock launcher?

Thanks in advance.

**Comment by Tamjow** [comment]
buy the game

**Comment by uberhalit** [comment]
I'll add a toggle to disable the auto-steam startup in the next version.

**Comment by Eerye** [comment]
If you have a pirated copy of the game then you don't need to worry about EAC by default... So no need to run it through the patcher.
Launch the game then the patcher and it'll hook into the game process automatically, just hit No when asked if you want to restart the game because it's already running.

Or am I misunderstanding the issue?

**Comment by mikeydoom** [comment]
I'm using a not official version of the game, and it doesn't open steam.

It's not this program, it's the crack you're using.

**Comment by uberhalit** [comment]
Added with v1.1.0.0
