### ISSUE TITLE
You can´t edit Game-Folder

### ISSUE THREAD

**Issue by o0Julia0o** [uberhalit/EldenRingFpsUnlockAndMore#89]
you have to search an appdata-folder to be able to delete the config - but not working all the time. Would be usefull, if the config would be next to the exe.

Gamepath-edit in the forms would be nice, too.

**Comment by uberhalit** [comment]
Hello, 

placing the `user.config` file into appdata is technically not done by the utility itself but by Microsoft. MS recommends using AppData since Windows 8. I had the config file next to the exe in my Sekiro-Utility. About 1-2x times per week users complained that the utility wouldn't save any settings, this went on for 2 years. Mostly because people had started the utility from inside an archive without properly extracting it, some others launched it from a write-protected folder and so on.

**Comment by o0Julia0o** [comment]
So an option would be the solution. Default = AppData, option set = next to the exe.
