### ISSUE TITLE
any reason why bitdefender detected it as a malware? 

### ISSUE THREAD

**Issue by Weemizo** [uberhalit/EldenRingFpsUnlockAndMore#94]
![image](https://user-images.githubusercontent.com/60063669/160245331-a511f094-7ffd-4753-9309-b19edef1056c.png)

**Comment by Weemizo** [comment]
and also after booting up my pc AV had to clean up system before booting up win10

**Comment by henderkes** [comment]
Because it patches memory in another process (eldenring.exe) and doesn't have a known signature. It's open source with the code being hosted on literally this repository, you're welcome to check and build yourself if you don't trust the tagged release.

**Comment by uberhalit** [comment]
Because AVs don't actually detect malicious exectuables, all they do is check if an application is manipulating/altering other programs or the system which is why a lot of patchers/cracks get false positives. As already stated the entire source code of this patcher is available (contrary to other tools), you can compile it yourself.
